@startuml "BUC4 - Gestionar Servicio (Sistema)"
left to right direction
skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam rectangle {
  BorderColor #7A1631
}
skinparam Arrow {
  Color #7A1631
}

actor "Administrador\ndel Sistema" as Admin

rectangle "EsperaRojo ULima" {
  usecase "Iniciar sesión\ncomo administrador" as UC1
  usecase "Gestionar rutas" as UC2
  usecase "Gestionar paraderos" as UC3
  usecase "Actualizar información\nde buses" as UC4
  usecase "Monitorear estado\ndel sistema" as UC5
}

Admin --> UC2
Admin --> UC3
Admin --> UC4
Admin --> UC5

UC2 ..> UC1 : <<include>>
UC3 ..> UC1 : <<include>>
UC4 ..> UC1 : <<include>>
UC5 ..> UC1 : <<include>>
@enduml
