@startuml
skinparam SwimlaneTitleBackgroundColor #EEE
skinparam ActivityBackgroundColor #FFF9C4
skinparam ActivityBorderColor #7A1631

|Usuario|
start
:Abre la aplicación;
:Ingresa correo y contraseña;
:Presiona "Iniciar sesión";

|Sistema|
:Validar credenciales;

if (¿Credenciales válidas?) then (Sí)

    if (¿Usuario registrado?) then (Sí)
        :Permitir acceso;
        :Mostrar pantalla principal;

        |Usuario|
        :Utiliza la aplicación;
        stop

    else (No)
        :Mostrar mensaje de usuario no registrado;
        stop
    endif

else (No)
    :Mostrar mensaje de error;
    stop
endif

@enduml